name: GitHub Readme YouTube Cards
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@1.8.0
        with:
          channel_id: UCipSxT7a3rn81vGLw9lqRkg
